-- =====================================
-- 01_DDL.sql
-- =====================================

/* 1. Create DW schema */
CREATE SCHEMA IF NOT EXISTS dw;

-- 1. DIM_SOURCES
CREATE TABLE IF NOT EXISTS dw.dim_sources (
    source_surr_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_name VARCHAR(100) NOT NULL,

    CONSTRAINT pk_dim_sources PRIMARY KEY (source_surr_id),
    CONSTRAINT uq_dim_sources_name UNIQUE (source_name)
);

-- 2. DIM_TRANSACTION_TYPES
CREATE TABLE IF NOT EXISTS dw.dim_transaction_types (
    transaction_type_surr_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_type VARCHAR(50) NOT NULL,

    CONSTRAINT pk_dim_transaction_types PRIMARY KEY (transaction_type_surr_id),
    CONSTRAINT uq_dim_transaction_types UNIQUE (transaction_type)
);

-- 3. DIM_CITIES
CREATE TABLE IF NOT EXISTS dw.dim_cities (
    city_surr_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name VARCHAR(100) NOT NULL,

    CONSTRAINT pk_dim_cities PRIMARY KEY (city_surr_id),
    CONSTRAINT uq_dim_cities UNIQUE (city_name)
);

-- 4. DIM_DATES
CREATE TABLE IF NOT EXISTS dw.dim_dates (
    date_surr_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_dt TIMESTAMP NOT NULL,
    date_year INT NOT NULL,
    date_month INT NOT NULL,
    date_day INT NOT NULL,
    date_hour INT NOT NULL,
    date_minute INT NOT NULL,
    date_day_of_week SMALLINT NOT NULL,

    CONSTRAINT pk_dim_dates PRIMARY KEY (date_surr_id),
    CONSTRAINT uq_dim_dates UNIQUE (date_dt),
    CONSTRAINT ck_dim_dates_month CHECK (date_month BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_dates_day CHECK (date_day BETWEEN 1 AND 31),
    CONSTRAINT ck_dim_dates_hour CHECK (date_hour BETWEEN 0 AND 23),
    CONSTRAINT ck_dim_dates_minute CHECK (date_minute BETWEEN 0 AND 59),
    CONSTRAINT ck_dim_dates_dow CHECK (date_day_of_week BETWEEN 1 AND 7)
);

-- 5. DIM_DISTRICTS
CREATE TABLE IF NOT EXISTS dw.dim_districts (
    district_surr_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_surr_id BIGINT NOT NULL,
    district_name VARCHAR(100) NOT NULL,

    CONSTRAINT pk_dim_districts PRIMARY KEY (district_surr_id),
    CONSTRAINT uq_dim_districts UNIQUE (city_surr_id, district_name),
    CONSTRAINT fk_dim_districts_city
        FOREIGN KEY (city_surr_id)
        REFERENCES dw.dim_cities (city_surr_id)
);

-- 6. DIM_APARTMENTS
CREATE TABLE IF NOT EXISTS dw.dim_apartments (
    apartment_surr_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street_address VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    url VARCHAR(500) NOT NULL,

    CONSTRAINT pk_dim_apartments PRIMARY KEY (apartment_surr_id),
    CONSTRAINT uq_dim_apartments_url UNIQUE (url)
);

-- 7. FCT_APARTMENTS
CREATE TABLE IF NOT EXISTS dw.fct_apartments (
    apartment_fct_surr_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_surr_id BIGINT NOT NULL,
    city_surr_id BIGINT NOT NULL,
    district_surr_id BIGINT NOT NULL,
    source_surr_id BIGINT NOT NULL,
    transaction_type_surr_id BIGINT NOT NULL,
    apartment_surr_id BIGINT NOT NULL,

    price DECIMAL(12,2) NOT NULL,
    price_per_sqm DECIMAL(10,2) NOT NULL,
    area_m2 DECIMAL(8,2) NOT NULL,
    bedrooms INT NOT NULL,
    floor INT NOT NULL,

    CONSTRAINT pk_fct_apartments PRIMARY KEY (apartment_fct_surr_id),

    CONSTRAINT fk_fct_date
        FOREIGN KEY (date_surr_id)
        REFERENCES dw.dim_dates (date_surr_id),

    CONSTRAINT fk_fct_city
        FOREIGN KEY (city_surr_id)
        REFERENCES dw.dim_cities (city_surr_id),

    CONSTRAINT fk_fct_district
        FOREIGN KEY (district_surr_id)
        REFERENCES dw.dim_districts (district_surr_id),

    CONSTRAINT fk_fct_source
        FOREIGN KEY (source_surr_id)
        REFERENCES dw.dim_sources (source_surr_id),

    CONSTRAINT fk_fct_transaction_type
        FOREIGN KEY (transaction_type_surr_id)
        REFERENCES dw.dim_transaction_types (transaction_type_surr_id),

    CONSTRAINT fk_fct_apartment
        FOREIGN KEY (apartment_surr_id)
        REFERENCES dw.dim_apartments (apartment_surr_id),

    CONSTRAINT ck_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_price_per_sqm_non_negative CHECK (price_per_sqm >= 0),
    CONSTRAINT ck_area_non_negative CHECK (area_m2 >= 0),
    CONSTRAINT ck_bedrooms_valid CHECK (bedrooms >= -1),
    CONSTRAINT ck_floor_valid CHECK (floor >= -1)
);
